### ISSUE TITLE
foundation.min.css not being built

### ISSUE THREAD

**Issue by dhornbein** [sahana/WACOP#11]
The data/time start/end inputs are inheriting the wrong style when `debug` mode is **off**.

![screen shot 2017-05-26 at 12 22 51 pm](https://cloud.githubusercontent.com/assets/358427/26503316/375b820c-420e-11e7-851d-69f141369fd5.png)

This screen shot is from `http://cad.aidiq.com/eden/event/event/1/custom`

![screen shot 2017-05-26 at 12 24 32 pm](https://cloud.githubusercontent.com/assets/358427/26503331/4f26a826-420e-11e7-8d8c-a044970f82f6.png)

While this screenshot is from `http://cad.aidiq.com/eden/event/event/1/custom?debug=1`

@flavour any idea why this is happening? It appears to also inherit the wrong color. I believe this might have something to do with the `settings.scss` file being rendered *before* another default settings file.

**Comment by flavour** [comment]
I can confirm the issue happens for me too.

If we look at debug mode, then we have:
themes/WACOP/foundation/foundation.css +2365
date modified 2017-04-06
background-color: #4D7EB9;
padding: 0.75rem 1.5rem 0.8125rem 1.5rem;

If we look at non-debug mode, then we have:
themes/WACOP/foundation/foundation.min.css 
date modified 2017-02-01
background-color: #008cba;
padding: 1rem 2rem 1.0625rem 2rem;

So it seems that the foundation.min.css hasn't been rebuilt

The CSS is compiled in 2 parts:
(1) SCSS -> CSS
Which is what you are doing using Compass
(2) CSS -> eden.min.css
Which is what I am doing using: https://github.com/sahana/eden/blob/master/static/scripts/tools/build.sahana.py
This makes no mention of foundation.css -> foundation.min.css

Unfortunately the wiki doesn't really go into much detail for custom foundation themes:
http://eden.sahanafoundation.org/wiki/DeveloperGuidelines/Themes#Complexmodifications
However looking at config.rb, this is what is supposed to build the .min version:
https://github.com/sahana/eden/blob/master/static/themes/WACOP/scss/config.rb

So this should therefore be your job!
I will add this missing part to the wiki:
compass compile -e production

**Comment by flavour** [comment]
I rebuilt the foundation.min.css so the issue is resovled for now, but we need to ensure this is part of routine workflow for future.
