### ISSUE TITLE
start/end date/time clear button should have X rather than text

### ISSUE THREAD

**Issue by dhornbein** [sahana/WACOP#12]
Date/time clear button currently has the text "clear" which gets squished to the right when the button is within a filter box that is small. The design calls for an X icon.

Replace the text with `<i class="fa fa-close"></i>`

**Comment by flavour** [comment]
I'm not sure on the usability of X to mean 'Clear' but I can make this a setting enabled just for WACOP if really desired

**Comment by flavour** [comment]
Actioned & Demo server updated
