### ISSUE TITLE
Post disappears when new comment is added

### ISSUE THREAD

**Issue by dhornbein** [sahana/WACOP#13]
From page: `http://cad.aidiq.com/eden/event/event/1/custom` when adding an additional comment to a post the post is removed after the comment is added. Only tested adding a comment to a post that already had comments.

Here's how it goes down:

1. click `add comment`
2. enter text and click `submit comment`
3. comment box is removed and spinner shows up
4. comments and parent post are removed from the view

**Comment by flavour** [comment]
The 'remove' is probably because the filters now exclude the parent post...I believe because it's timestamp is changed...I agree this is a usability issue & there's no reason why adding a comment to a post should change the post's timestamp. I will investigate further.

**Comment by flavour** [comment]
Wasn't timestamps, the system thought it should filter it out indeed, but because the list_id didn't match
