### ISSUE TITLE
Event/Incident profile directory and task tab's search not working

### ISSUE THREAD

**Issue by dhornbein** [sahana/WACOP#16]
Search label has no corresponding search field.

![screen shot 2017-06-30 at 12 02 49 pm](https://user-images.githubusercontent.com/358427/27744073-3304e1e6-5d8c-11e7-9475-df854086ac6c.png)

The following view files:

- `/modules/templates/WACOP/views/incident_profile.html`
- `/modules/templates/WACOP/views/event_profile.html`

the code that builds the builds the search is:

```
<label for='event_organisation-search' class='prefix'>Search</label>
<div id='dt-search-event_organisation'></div>
```

The HTML pattern for search boxes looks like this:

```
<div class="search-wrapper">
    <input type="text" name="filter-test" placeholder="Search">
    <span class="search-icon"><i class="fa fa-search"></i></span>
</div>
```

*note: the HTML layout has been updated but as of posting has not be submitted in a pull request*

**Comment by flavour** [comment]
The styling has been updated across the event profile & incident profile pages & the search box has been restored. I also had to do some work to get these to work with the clickable name field.
There needs to be some CSS work to fixup the style as the search icon isn't attached to the search INPUT properly
