### ISSUE TITLE
Directory search boxes mangled by .dataTables_filter

### ISSUE THREAD

**Issue by dhornbein** [sahana/WACOP#19]
The search boxes within the directories tabs: staff, organizations, and tasks are being malformed by the application of `dataTables_filter` class. This class is acting on them using some `!important` css tags which makes overwriting them challenging. Rather than overwrite the css attributes I'd rather this element not have the class name applied.

from `modules/templates/WACOP/views/updates_directories.html`
```html
         {{=create_event_human_resource_popup}}
         <div class='panel'>
           <div class='search-wrapper' id='dt-search-event_human_resource'>
             <span class='search-icon'><i class='fa fa-search'></i></span>
           </div>
         </div>
```

I think the element is being targeted via the `id` and the class is being applied along with the input box.

**Comment by flavour** [comment]
Fixed: https://github.com/sahana/eden/commit/c1c99f083d5792c3c5c24a796f043fdb44626497
