### ISSUE TITLE
Groups page initial setup

### ISSUE THREAD

**Issue by dhornbein** [sahana/WACOP#24]
@flavour can you add the base setup for the [groups/group page](https://sites.google.com/sahanafoundation.org/wacopdesign/groups/group) page so I can create the view file for it?

**Comment by flavour** [comment]
ok, done...group_browse.html & group_profile.html are now available in the WACOP/views folder
These can be accessed via the URLs /eden/pr/forum/browse & /eden/pr/forum/x/custom
These are empty right now, so dummy data can be generated using the std /eden/pr/forum functions.

Sorry this took so long, but needed to think through the best way to approach this requirement...it's basically pr_group but that's already used by Resources, so needed to create a new one, so have come up with pr_forum (Currently this doesn't filter the list of Persons to those with a User Accounts, but it will do so)

**Comment by devinbalkind** [comment]
Nice work guys.

**Comment by dhornbein** [comment]
I'm building out the pages now. @flavour how can I view the groups pages? What's the URL?

**Comment by flavour** [comment]
As above: "These can be accessed via the URLs /eden/pr/forum/browse & /eden/pr/forum/x/custom"

**Comment by dhornbein** [comment]
I've pushed the HTML views to Eden.
