### ISSUE TITLE
Login/out message being swallowed by design

### ISSUE THREAD

**Issue by flavour** [sahana/WACOP#26]
See http://prntscr.com/h6kcsy

**Comment by dhornbein** [comment]
I'm using CSS to display these notifications as fixed under the nav bar like so:

![screen shot 2018-01-05 at 6 45 22 pm](https://user-images.githubusercontent.com/358427/34751117-bc99742e-f578-11e7-81a5-b6e57269fb3d.png)

I'll send this update up as a pull request soon unless there is any coordination you'd like to make @flavour

**Comment by flavour** [comment]
PR should be fine...not sure what other coordination there could be

**Comment by flavour** [comment]
Maybe just checking that this addresses the other issue we currently have with alerts, that the very long pages in WACOP, where we often work at the bottom of the page mean that the alerts in the top of the page never get seen.
Am not sure if the Alerts should be displayed only in the viewport or else we scroll the page to the alert...the 2nd seems like it could be annoyingly jarring, so perhaps the 1st...which I'm not sure if your design covers?

**Comment by dhornbein** [comment]
The alerts are attached to the fixed nav bar so they will always appear in the top right of the view port.

PR: https://github.com/sahana/eden/pull/1442
