### ISSUE TITLE
Browse Event Page Structure

### ISSUE THREAD

**Issue by dhornbein** [sahana/WACOP#6]
The Event Browse page ([mock up here](https://sites.google.com/sahanafoundation.org/wacopdesign/events)) contains site wide alerts, 3 recent events, a filterable map, and a table of events.

# Page Structure

```html
<main role='main' class='main'>  
  {{=XML(alerts)}}
  {{=XML(events)}}
  <!-- Event map -->
  <div class='row well'>
    <div class='medium-4 columns'>
      <!-- Event map filter goes here -->
    </div>
    <div class='medium-8 columns'>
      <!-- Event map goes here -->
    </div>
  </div>
  <!-- End Event map -->

  <!-- Event list -->
  <div class='row well'>
    <h3>Events</h3>
    <!-- Event list goes here -->
  </div>
  <!-- End Event map -->

</main>
```

# Mockup

*Note: This image is a published version of a google drawing, and should reflect the most recent changes*

![event-browse-mock-up](https://docs.google.com/drawings/d/1J3XKat6pmVh-mESPB8xoW3xNvkL4DgbLS22pVmrVOjY/pub?w=1150&h=1434)

**Comment by flavour** [comment]
Event column at the end of the dataTable obviously makes no sense for Events

**Comment by devinbalkind** [comment]
#truth.

Here are the fields the table should have: https://airtable.com/shrVNYlmZn3VBuwcM

For the Incidents and Resources column on the right, those should be number of incidents and resources.

**Comment by flavour** [comment]
is there a list of which filters we should have?

**Comment by devinbalkind** [comment]
Yes: https://airtable.com/shrVWuHeARvL6GL83

The fields there are ones to be filtered/searchable. Does that make sense?
