### ISSUE TITLE
Taggit autocomplete returns empty list

### ISSUE THREAD

**Issue by dhornbein** [sahana/WACOP#8]
When entering new tags the auto complete feature displays empty containers where suggestions should go.

![screen shot 2017-04-28 at 10 20 32 am](https://cloud.githubusercontent.com/assets/358427/25532822/9f2b6dfc-2bfc-11e7-9dca-beaa87ec15e1.png)

Note: the attribute `autocomplete="off"` appears to be set.

**Comment by flavour** [comment]
Indeed, currently off: https://github.com/sahana/eden/blob/master/static/themes/WACOP/js/update_tags.js#L16
So perhaps an upstream issue to resolve (or just patch ourselves if upstream won't)

**Comment by flavour** [comment]
Sorry, wrong link...that one is for create/update forms.
The correct link is here, so autocomplete is on:
https://github.com/sahana/eden/blob/master/modules/templates/WACOP/controllers.py#L950
We could just disable it?

**Comment by devinbalkind** [comment]
I'm a big fan of Auto complete so let's keep and fix it.

**Comment by dhornbein** [comment]
This is working now
